# Generated by Django 3.2.13 on 2022-06-29 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_lms_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramIntent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('program_uuid', models.UUIDField()),
                ('reason', models.CharField(max_length=255)),
                ('certainty', models.CharField(choices=[('CERTAIN_YES', 'CERTAIN_YES'), ('CERTAIN_NO', 'CERTAIN_NO'), ('MAYBE', 'MAYBE')], max_length=255)),
                ('effective_timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'program intent',
                'db_table': 'programintent_programintent',
                'unique_together': {('user', 'program_uuid', 'reason', 'certainty', 'effective_timestamp')},
            },
        ),
    ]
