# Generated by Django 3.2.13 on 2022-06-28 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_lms_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramIntent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('program_uuid', models.UUIDField()),
                ('reason', models.CharField(choices=[('CC', 'All Courses Complete'), ('BP', 'Bundle Purchase'), ('CE', 'All Courses Enrolled')], max_length=2)),
                ('certainty', models.CharField(choices=[('Y', 'Certainly Yes'), ('N', 'Certainly No'), ('M', 'Maybe')], max_length=1)),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'program intent',
                'db_table': 'programintent_programintent',
                'unique_together': {('user', 'program_uuid', 'reason', 'certainty', 'effective_date')},
            },
        ),
    ]
