# Generated by Django 3.2.13 on 2022-07-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_programintent'),
    ]

    operations = [
        migrations.AddField(
            model_name='programintent',
            name='lms_user_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='programintent',
            unique_together={('lms_user_id', 'program_uuid', 'reason', 'certainty', 'effective_timestamp')},
        ),
        migrations.RemoveField(
            model_name='programintent',
            name='user',
        ),
    ]
