# Generated by Django 3.2.13 on 2022-07-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_programintent_lms_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programintent',
            name='lms_user_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
